language: node_js
node_js:
    - 10
install:
    - yarn
script:
    - yarn build
after_success:
    - cd docs/.vuepress/dist
    - git init
    - git config --global user.name "hebin"
    - git config --global user.email "68621828@qq.com"
    - git add -A
    - git commit -m 'deploy'
    - git push --quiet --force "https://d5bb52c9b8cce10430b6c76059c710e6ef244965@github.com/coolpail" master:gh-pages
