language: node_js
node_js:
    - 10
install:
    - yarn
script:
    - yarn build
after_success:
    - cd docs/.vuepress/dist
    - git init
    - git config --global user.name "hebin"
    - git config --global user.email "68621828@qq.com"
    - git add -A
    - git commit -m 'deploy'
    - git push --quiet --force "https://${gh_token}@${GH_REF}" master:gh-pages
