language: node_js
node_js:
    - 10
git:
    submodules: false

before_install:
    - sed -i 's/git@github.com:/git:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive
install:
    - yarn
script:
    - yarn build
after_success:
    - cd docs/.vuepress/dist
    - git init
    - git config --global user.name "${U_NAME}"
    - git config --global user.email "${U_EMAIL}"
    - git add -A
    - git commit -m 'deploy'
    - git push --quiet --force "${GITHUB_TOKEN}@${GH_REF}" master:${P_BRANCH}
